# Generated by Django 4.2.2 on 2023-07-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dateCreation',
            new_name='dataCreation',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentUser',
            new_name='userPost',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dateCreation',
            new_name='dataCreations',
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'News'), ('AR', 'Article')], default='AR', max_length=20),
        ),
    ]
